### ISSUE TITLE
initializers.py (getconfig method)

### ISSUE THREAD

**Issue by scuenat** [NEGU93/cvnn#3] opened 2021-01-25 06:26 UTC
Hi, I've just started as a PhD student. I work with holograms. That's why I thought I could try your framework to train a model in the complex space instead of the real space. 

When running my code I encountered an issue with this method. It says that the "seed" is not a valid argument. I modified the code as follows and it seems to work now. I wanted to propose a pull-request, but the functionality is blocked.

![image](https://user-images.githubusercontent.com/7954858/105668895-85794500-5ede-11eb-80a8-0a0cd67eb3f6.png)

**Comment by NEGU93** [comment] 2021-01-25 09:27
Hi @scuenat I am glad you find my library useful. Please, don't forget to cite it if you use it in any publication code.

Strange that you could not do a PL, I'll check that.

The issue is fixed in this [commit](https://github.com/NEGU93/cvnn/commit/6c1e5bf233bd77397cf78fb7ca538d775f38755f), thanks for pointing it out.

**Closed** 2021-01-25 09:29 UTC
